//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int IdAppointment { get; set; }
        public int IdMedicalCard { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> IdStaff { get; set; }
    
        public virtual MedicalCard MedicalCard { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
