//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentData
    {
        public Nullable<System.DateTime> DateTime { get; set; }
        public string FirstName { get; set; }
        public string NamePet { get; set; }
        public int IdAppointment { get; set; }
        public int IdClient { get; set; }
        public int IdPet { get; set; }
        public Nullable<int> IdStaff { get; set; }
        public int IdMedicalCard { get; set; }
    }
}
